#! /usr/bin/env bash

# jbw created 2018.04.29
# This is jank. The robust way would be to make a listing of all the files, and
# then subselect those which are essentially identical except for an integer
# value at the end of the file and before the mp3 extension. even then, you
# would need special cases for episodes, or movements, ... ugh, what a pain

function data_handler() {
    echo "command: $1"
    for n in 1 2 3 4 5 6 7 8 9 10
    do
        echo "$n"
        find . -type f -iname "* $n.mp3" -print0 |\
            grep -iv "pt\. $n.mp3" |\
            grep -iv "part $n.mp3" |\
            grep -iv "Episode" |\
            grep -iv "Track" |\
            grep -iv "Dancier" |\
            grep -iv "Melody" |\
            grep -iv "3 X 3"
    done
}

# TODO. make this switch work :(

if [[ "$1" == "--remove" ]]
then
    echo "Removing duplicates..."
    data_handler "rm"
else
    echo "Listing duplicates..."
    data_handler "echo"
fi
