#!/bin/bash

# dudir - recursive directory size listing
# TODO add max depth option

# check cl args: -r = copy, -h message
RECURSE="false"
for arg; do
    if [[ "$arg" = "-r" ]]; then
        RECURSE="true"
    elif [[ "$arg" = "-h" ]]; then
        printf "dudir - folder sizing tool usage:\n"
        printf "\t-r recursively sie folders/content\n"
        printf "\t-h display this message\n"
        exit 1
    fi
done

# sed terminal colors
CYAN=`echo -e "\033[0;36m"`
UCYAN=`echo -e "\033[4;36m"`
GREEN=`echo -e "\033[0;32m"`
UGRN=`echo -e "\033[4;32m"`
RESET=`echo -e "\033[0;0m"`

function sizer # get size of folders/files given a directory
{
    echo "$UCYAN[mb]$RESET	${UCYAN}($1)$RESET"
    du -smc $1/* | sort -nr | colorer
    echo
}

function colorer # color the size of the folder/item
{
    sed -e "
    /^[0-9]/{
        s_^\([0-9][0-9]*\)_$GREEN\1${RESET}_g
    }
    s_\(total\)_$UGRN\1${RESET}_g
    "
}

# inform of base, recursion
echo "root dir: $UCYAN$(pwd)$RESET"
echo "recursion: $UCYAN$RECURSE$RESET"
echo

# get all folders, size
if [[ $RECURSE == "true" ]]; then

    folders=$(find . -type d | grep -v '^\./\.')
    for folder in ${folders[@]}; do
        sizer $folder
    done

else # just size pwd
    sizer .
fi
