#!/usr/bin/env bash

# convert a git remote (on github) to use https or ssh (pass in)
# run this in the base directory of the git repo (where .git/ lives)

function checkargs
{
    echo 'usage: remote-setter [https|ssh]'
    exit 1
}

# wrong number args (not 2) given
[[ $# != 1 ]] && checkargs

# parsing command line arguments
HOST='github.com' # TODO: autodetect this
protocol="$1" # either ssh or https

# get current user and repo info
USER=$(git config --global --get user.user)
REPO=$(basename "`pwd`")

if [[ $protocol == 'https' ]]; then # switching over to https
    git remote set-url origin https://$HOST/$USER/$REPO.git
elif [[ $protocol == 'ssh' ]]; then # switching over to ssh
    git remote set-url origin git@$HOST:$USER/$REPO.git
else # strange things are happening
    checkargs
fi

# show new remote URL
#echo user: $USER
#echo repo: $REPO
echo New remotes:
git remote -v

