#!/usr/bin/env perl

use strict;

# args - oldext, newext
my $usage = "usage: mvext <old> <new>\n";
die $usage unless (@ARGV == 2);
my ($oExt, $nExt) = @ARGV;

# actually perform the move
print "Moving $oExt -> $nExt\n";
my @old = glob "*.$oExt";
foreach my $f (@old){
	my $new = $f;
	$new =~ s/($oExt)$/$nExt/;
	print "\tMoving ($f) -> $new\n";
	rename $f, $new;
}
