#!/bin/bash

# dot - jeremy warner
# dotfile management script
# -c copies instead of links
# -b = backup, -h (options)

# grab all dotfiles
DFPATH=~/Code/dotfiles

# dynamically load all dotfiles
dotfiles=$(ls $DFPATH | grep -Ev 'etc|readme|oh-my-zsh|vim$')

# dynamic way to get runtime folder
TOOLPATH=$(cd "${0%/*}/"; pwd)

# check cl args: -c = copy, -b = backup, -h message
for arg; do

    if [[ "$arg" = "-c" ]]; then
        COPY="true";
    elif [[ "$arg" = "-b" ]]; then
        mkdir -p $DFPATH/backup/
        BKUP="true";
    elif [[ "$arg" = "-h" ]]; then
        printf "dot - dotfile management script. usage: \n";
        printf "\t-c copy files instead of linking them\n";
        printf "\t-b back up files into backup folder\n";
        printf "\t-h display this message\n" && exit 1;
    fi

done

# if -c specified, copy files to ~
if [[ $COPY ]]; then

    printf "\nCopying dotfiles from source to home...\n\n"
    for dot in ${dotfiles[@]}; do
        [[ $BKUP ]] && mv ~/.$dot $DFPATH/backup/$dot || rm -f ~/.$dot
        cp -va $DFPATH/$dot  ~/.$dot
    done

else # else link them to home directory

    printf "\nLinking dotfiles from source to home...\n"
    for dot in ${dotfiles[@]}; do
        [[ $BKUP ]] && mv ~/.$dot $DFPATH/backup/$dot || rm -f ~/.$dot
        ln -Fsv $DFPATH/$dot  ~/.$dot
    done

fi

# move the vim and zsh directory (yay themes and bundles)
printf "\nCopying .oh-my zsh, vim folders to home dir...\n\n"
cp -a $DFPATH/oh-my-zsh/. ~/.oh-my-zsh/
cp -a $DFPATH/vim/. ~/.vim/
