#!/usr/bin/perl -w

use strict;

# by jeremy warner
# open up a website or search in google chrome from cli

my $domains = 'io|com|web|net|org|gov|edu';

if(!@ARGV){ # if no arg entered, inform them of tool usage
    print "web - google chrome cli launcher for MacOSX. usage:\n";
    print "\tParsing domains ($domains)\n";
    print "\tno site\tsearches google.com with the supplied args\n";
    print "\tsite: open up link to web address given\n";
}

# look up urls or search the terms user provided
# foreach my $arg (@ARGV) { print $arg, "\n"; }
my $siteAddress;
my $siteCount;
foreach(@ARGV){

    # check if address being passed in
    if(/\.($domains)/){
        #print "Opening arguments as websites...\n";
        system 'open -a "Google Chrome"'." 'http://$_'";
        $siteCount++; next; # after flagging, address check for more
    }

    # no address matched, concatenate search terms, execute
    if($siteCount){ shift @ARGV foreach (1..$siteCount); }
    my $search = join ' ', @ARGV;
    $search = "'https://www.google.com/search?q=$search'";
    system 'open -a "Google Chrome" '.$search;
    last; # query has been completed, time for byebye

}
