#!/usr/bin/env zsh

df_path=~/GitHub/dotfiles
#df_path=$(cd "${0%/*}/.."; pwd)

cd $df_path
vim zshrc
git add zshrc
git commit -v
ln -Fsv $df_path/zshrc ~/.zshrc
git push origin master
cd -

printf "\nzshrc update complete.\n"
